#cloud-config
---

write_files:
  - path: /opt/bin/kubernetes-install.sh
    owner: root
    permissions: 0755
    content: |
      #! /usr/bin/bash
      
      if [ ! -f /opt/bin/kubelet ]; then
        echo "Kubenetes not installed - installing."

        # Extract the Kubernetes binaries.
        sudo wget -N -P /opt/bin http://storage.googleapis.com/kubernetes-release/release/v1.1.2/bin/linux/amd64/kubectl
        sudo wget -N -P /opt/bin http://storage.googleapis.com/kubernetes-release/release/v1.1.2/bin/linux/amd64/kubelet
        sudo chmod +x /opt/bin/kubelet /opt/bin/kubectl
      fi

  - path: /opt/bin/calico-install.sh
    owner: root
    permissions: 0755
    content: |
      #! /usr/bin/bash
      
      if [ ! -f /opt/bin/calicoctl ]; then
        echo "Calico not installed - installing."
       
        # Install the `calicoctl` binary
        wget -P /opt/bin http://www.projectcalico.org/builds/calicoctl 
        chmod +x /opt/bin/calicoctl
      fi

  - path: /opt/bin/install-manifests.sh
    owner: root
    permissions: 0755
    content: |
      #! /usr/bin/bash
      
      # Ensure directories exists.
      sudo mkdir -p /etc/kubernetes/manifests/
      sudo mkdir -p /etc/kubernetes/ssl/
      sudo mkdir -p /etc/kubernetes/addons/
      
        # Download config.
        sudo wget -N -P /etc/kubernetes/manifests/ https://raw.githubusercontent.com/projectcalico/calico-kubernetes/master/config/master/kubernetes-master.manifest
        sudo wget -N -P /etc/kubernetes/manifests/ https://raw.githubusercontent.com/projectcalico/calico-kubernetes/master/config/master/calico-etcd.manifest
        sudo wget -N -P /etc/kubernetes/addons/ https://raw.githubusercontent.com/projectcalico/calico-kubernetes/master/config/master/dns/skydns.yaml
      fi

      # Insert the master's IP address into the manifest.
      sudo sed -i -e "s/<PRIVATE_IPV4>/$private_ipv4/g" /etc/kubernetes/manifests/calico-etcd.manifest
  - path: /etc/kubernetes/manifests/kubernetes-master.manifest
    owner: core
    permissions: 0644
    content: |
      <CA_CERT>

coreos:

  update:
    reboot-strategy: off
  units:
    - name: manifest-install.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Installs Manifests 
        After=network-online.target
        Requires=network-online.target

        [Service]
        ExecStart=/opt/bin/install-manifests.sh
        RemainAfterExit=yes
        Type=oneshot

    - name: kubernetes-install.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Installs Kubernetes tools
        After=manifest-install.service
        Requires=manifest-install.service

        [Service]
        ExecStart=/opt/bin/kubernetes-install.sh
        RemainAfterExit=yes
        Type=oneshot

    - name: kubelet.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes
        Requires=docker.service,kubernetes-install.service
        After=kubernetes-install.service
  
        [Service]
        ExecStart=/opt/bin/kubelet \
        --register-node=false \
        --allow-privileged=true \
        --config=/etc/kubernetes/manifests \
        --cluster-dns=10.100.0.10 \
        --cluster_domain=cluster.local \
        --logtostderr=true
        Restart=always
        RestartSec=10
  
        [Install]
        WantedBy=multi-user.target

    - name: calico-install.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Installs Calico tools
        After=kubelet.service
        Requires=kubelet.service

        [Service]
        ExecStart=/opt/bin/calico-install.sh
        RemainAfterExit=yes
        Type=oneshot

    - name: calico-node.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=calicoctl node
        After=docker.service
        Requires=docker.service
        
        [Service]
        User=root
        Environment="ETCD_AUTHORITY=127.0.0.1:6666"
        PermissionsStartOnly=true
        ExecStart=/opt/bin/calicoctl node --detach=false
        Restart=always
        RestartSec=10
    
        [Install]
        WantedBy=multi-user.target
