apiVersion: v1
kind: ReplicationController
metadata:
  name: pinger
  labels:
    k8s-app: pinger
spec:
  replicas: 0
  selector:
    k8s-app: pinger
  template:
    metadata:
      labels:
        k8s-app: pinger
    spec:
      nodeSelector:
        role: node
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: Never
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
        command:
        - /bin/sh 
        - -c 
        - 'wget -T 10 -q -O - kube-scale-master:8080 || wget -T 10 -q -O - kube-scale-master:8080 || wget -T 10 -q -O - kube-scale-master:8080 || exit;sleep 99999'
